"use client";

import { createContext, useState, useContext } from 'react';

const translations = {
  en: {
    nav_home: "Home",
    nav_records: "Records",
    nav_visits: "Visits",
    nav_profile: "Profile",
    nav_health: "Health",
    h_title: "Med-Vault",
    h_greeting: "Hallo",
    h_sub_greeting: "Your vitality looks excellent today. Here is your curated wellness overview.",
    h_upload_new: "Upload New",
    h_upload_desc: "Add to vault",
    h_view_vault: "View Vault",
    h_view_desc: "Access records",
    h_med_tracker: "Medicine Tracker",
    h_view_all: "View All",
    h_med1_name: "Lisinopril",
    h_med1_desc: "10mg • After breakfast",
    h_med2_name: "Vitamin D3",
    h_med2_desc: "5000 IU • With dinner",
    h_next_visit: "Next Visit",
    h_visit1_tag: "Upcoming",
    h_visit1_title: "Dr. Sarah Jenkins",
    h_visit1_desc: "General Checkup • 10:00 AM",
    h_visit2_tag: "Pending",
    h_visit2_title: "Lab Results",
    h_visit2_desc: "Blood panel • Expected Tomorrow",
    v_title: "Health Vault",
    v_header: "My Records",
    v_desc: "Access and manage your complete medical history in one secure place.",
    v_search: "Search records, dates, or doctors...",
    v_month1: "October 2023",
    v_rec1_title: "Comprehensive Blood Panel",
    v_rec1_desc: "Dr. Sarah Jenkins • Lab Report",
    v_rec1_date: "Oct 24",
    v_rec2_title: "Chest X-Ray Scans",
    v_rec2_desc: "City General Hospital • Radiology",
    v_rec2_date: "Oct 12",
    v_month2: "September 2023",
    v_rec3_title: "Annual Physical Summary",
    v_rec3_desc: "Dr. Robert Chen • General Practice",
    v_rec3_date: "Sep 05",
    v_rec4_title: "Vaccination Record",
    v_rec4_desc: "Pharmacy Plus • Immunization",
    v_rec4_date: "Sep 01",
    p_title: "MedVault",
    p_patient_id: "Patient ID: #29402",
    p_verified: "Verified Patient",
    p_grp_account: "Account",
    p_personal_info: "Personal Info",
    p_med_records: "Medical Records",
    p_insurance: "Insurance",
    p_grp_pref: "Preferences",
    p_language: "Language",
    p_notifications: "Notifications",
    p_security: "Security",
    p_grp_support: "Support",
    p_help: "Help Center",
    p_contact: "Contact Us",
    p_signout: "Sign Out"
  },
  hi: {
    nav_home: "होम",
    nav_records: "रिकॉर्ड",
    nav_visits: "विज़िट",
    nav_profile: "प्रोफ़ाइल",
    nav_health: "स्वास्थ्य",
    h_title: "मेड-वॉल्ट",
    h_greeting: "नमस्ते",
    h_sub_greeting: "आज आपकी जीवन शक्ति बेहतरीन लग रही है। यहाँ आपका स्वास्थ्य अवलोकन है।",
    h_upload_new: "नया अपलोड करें",
    h_upload_desc: "वॉल्ट में जोड़ें",
    h_view_vault: "वॉल्ट देखें",
    h_view_desc: "रिकॉर्ड एक्सेस करें",
    h_med_tracker: "मेडिसिन ट्रैकर",
    h_view_all: "सभी देखें",
    h_med1_name: "लिशिनोप्रिल",
    h_med1_desc: "10mg • नाश्ते के बाद",
    h_med2_name: "विटामिन D3",
    h_med2_desc: "5000 IU • रात के खाने के साथ",
    h_next_visit: "अगली विज़िट",
    h_visit1_tag: "आने वाली",
    h_visit1_title: "डॉ. सारा जेनकिंस",
    h_visit1_desc: "सामान्य जांच • सुबह 10:00 बजे",
    h_visit2_tag: "लंबित",
    h_visit2_title: "लैब परिणाम",
    h_visit2_desc: "रक्त पैनल • कल अपेक्षित",
    v_title: "हेल्थ वॉल्ट",
    v_header: "मेरे रिकॉर्ड",
    v_desc: "अपने संपूर्ण चिकित्सा इतिहास को एक सुरक्षित स्थान पर एक्सेस और प्रबंधित करें।",
    v_search: "रिकॉर्ड, तिथियां या डॉक्टर खोजें...",
    v_month1: "अक्टूबर 2023",
    v_rec1_title: "व्यापक रक्त पैनल",
    v_rec1_desc: "डॉ. सारा जेनकिंस • लैब रिपोर्ट",
    v_rec1_date: "अक्टू 24",
    v_rec2_title: "चेस्ट एक्स-रे स्कैन",
    v_rec2_desc: "सिटी जनरल अस्पताल • रेडियोलॉजी",
    v_rec2_date: "अक्टू 12",
    v_month2: "सितंबर 2023",
    v_rec3_title: "वार्षिक शारीरिक सारांश",
    v_rec3_desc: "डॉ. रॉबर्ट चेन • सामान्य अभ्यास",
    v_rec3_date: "सितं 05",
    v_rec4_title: "टीकाकरण रिकॉर्ड",
    v_rec4_desc: "फार्मेसी प्लस • टीकाकरण",
    v_rec4_date: "सितं 01",
    p_title: "मेड-वॉल्ट",
    p_patient_id: "रोगी आईडी: #29402",
    p_verified: "सत्यापित रोगी",
    p_grp_account: "खाता",
    p_personal_info: "व्यक्तिगत जानकारी",
    p_med_records: "चिकित्सा रिकॉर्ड",
    p_insurance: "बीमा",
    p_grp_pref: "प्राथमिकताएं",
    p_language: "भाषा",
    p_notifications: "सूचनाएं",
    p_security: "सुरक्षा",
    p_grp_support: "समर्थन",
    p_help: "सहायता केंद्र",
    p_contact: "संपर्क करें",
    p_signout: "साइन आउट"
  },
  bn: {
    nav_home: "হোম",
    nav_records: "রেকর্ড",
    nav_visits: "ভিজিট",
    nav_profile: "প্রোফাইল",
    nav_health: "স্বাস্থ্য",
    h_title: "মেড-ভল্ট",
    h_greeting: "নমস্কার",
    h_sub_greeting: "আজ আপনার জীবনীশক্তি চমৎকার দেখাচ্ছে। এখানে আপনার সুস্থতার ওভারভিউ।",
    h_upload_new: "নতুন আপলোড",
    h_upload_desc: "ভল্টে যোগ করুন",
    h_view_vault: "ভল্ট দেখুন",
    h_view_desc: "রেকর্ড অ্যাক্সেস করুন",
    h_med_tracker: "মেডিসিন ট্র্যাকার",
    h_view_all: "সব দেখুন",
    h_med1_name: "লিসিনোপ্রিল",
    h_med1_desc: "10mg • প্রাতঃরাশের পর",
    h_med2_name: "ভিটামিন D3",
    h_med2_desc: "5000 IU • রাতের খাবারের সাথে",
    h_next_visit: "পরবর্তী ভিজিট",
    h_visit1_tag: "আসন্ন",
    h_visit1_title: "ড. সারা জেনকিন্স",
    h_visit1_desc: "সাধারণ চেকআপ • সকাল ১০:০০",
    h_visit2_tag: "অমীমাংসিত",
    h_visit2_title: "ল্যাব ফলাফল",
    h_visit2_desc: "রক্ত প্যানেল • আগামীকাল প্রত্যাশিত",
    v_title: "হেলথ ভল্ট",
    v_header: "আমার রেকর্ড",
    v_desc: "একটি সুরক্ষিত জায়গায় আপনার সম্পূর্ণ চিকিৎসা ইতিহাস পরিচালনা করুন।",
    v_search: "রেকর্ড, তারিখ বা ডাক্তার খুঁজুন...",
    v_month1: "অক্টোবর ২০২৩",
    v_rec1_title: "ব্যাপক রক্ত প্যানেল",
    v_rec1_desc: "ড. সারা জেনকিন্স • ল্যাব রিপোর্ট",
    v_rec1_date: "অক্টো ২৪",
    v_rec2_title: "বুকের এক্স-রে স্ক্যান",
    v_rec2_desc: "সিটি জেনারেল হাসপাতাল • রেডিওলজি",
    v_rec2_date: "অক্টো ১২",
    v_month2: "সেপ্টেম্বর ২০২৩",
    v_rec3_title: "বার্ষিক শারীরিক সারাংশ",
    v_rec3_desc: "ড. রবার্ট চেন • সাধারণ অনুশীলন",
    v_rec3_date: "সেপ্টে ০৫",
    v_rec4_title: "টিকাকরণ রেকর্ড",
    v_rec4_desc: "ফার্মেসি প্লাস • অনাক্রম্যকরণ",
    v_rec4_date: "সেপ্টে ০১",
    p_title: "মেড-ভল্ট",
    p_patient_id: "রোগী আইডি: #29402",
    p_verified: "যাচাইকৃত রোগী",
    p_grp_account: "অ্যাকাউন্ট",
    p_personal_info: "ব্যক্তিগত তথ্য",
    p_med_records: "চিকিৎসা রেকর্ড",
    p_insurance: "বীমা",
    p_grp_pref: "পছন্দসমূহ",
    p_language: "ভাষা",
    p_notifications: "বিজ্ঞপ্তি",
    p_security: "নিরাপত্তা",
    p_grp_support: "সমर्थন",
    p_help: "সাহায্য কেন্দ্র",
    p_contact: "যোগাযোগ করুন",
    p_signout: "সাইন আউট"
  },
  ta: {
    nav_home: "முகப்பு",
    nav_records: "பதிவுகள்",
    nav_visits: "வருகைகள்",
    nav_profile: "சுயவிவரம்",
    nav_health: "ஆரோக்கியம்",
    h_title: "மெட்-வால்ட்",
    h_greeting: "வணக்கம்",
    h_sub_greeting: "இன்று உங்கள் ஆற்றல் சிறப்பாக உள்ளது. உங்கள் நலவாழ்வு கண்ணோட்டம் இங்கே.",
    h_upload_new: "புதிய பதிவேற்றம்",
    h_upload_desc: "வால்ட்டில் சேர்க்க",
    h_view_vault: "வால்ட் பார்க்க",
    h_view_desc: "பதிவுகளை அணுக",
    h_med_tracker: "மருந்து டிராக்கர்",
    h_view_all: "அனைத்தும் காண்க",
    h_med1_name: "லிசினோபிரில்",
    h_med1_desc: "10mg • காலை உணவிற்குப் பின்",
    h_med2_name: "வைட்டமின் D3",
    h_med2_desc: "5000 IU • இரவு உணவோடு",
    h_next_visit: "அடுத்த வருகை",
    h_visit1_tag: "வரவிருக்கும்",
    h_visit1_title: "டாக்டர் சாரா ஜென்கின்ஸ்",
    h_visit1_desc: "பொது பரிசோதனை • காலை 10:00",
    h_visit2_tag: "நிலுவையில் உள்ளது",
    h_visit2_title: "ஆய்வக முடிவுகள்",
    h_visit2_desc: "இரத்த குழு • நாளை எதிர்பார்க்கப்படுகிறது",
    v_title: "ஹெல்த் வால்ட்",
    v_header: "என் பதிவுகள்",
    v_desc: "உங்கள் முழு மருத்துவ வரலாற்றையும் ஒரு பாதுகாப்பான இடத்தில் நிர்வகிக்கவும்.",
    v_search: "பதிவுகள், தேதிகள், மருத்துவர்களை தேடுக...",
    v_month1: "அக்டோபர் 2023",
    v_rec1_title: "விரிவான இரத்த குழு",
    v_rec1_desc: "டாக்டர் சாரா ஜென்கின்ஸ் • ஆய்வக அறிக்கை",
    v_rec1_date: "அக் 24",
    v_rec2_title: "மார்பு எக்ஸ்-ரே ஸ்கேன்",
    v_rec2_desc: "சிட்டி பொது மருத்துவமனை • கதிரியக்கவியல்",
    v_rec2_date: "அக் 12",
    v_month2: "செப்டம்பர் 2023",
    v_rec3_title: "வருடாந்திர உடல் சுருக்கம்",
    v_rec3_desc: "டாக்டர் ராபர்ட் சென் • பொது பயிற்சி",
    v_rec3_date: "செப் 05",
    v_rec4_title: "தடுப்பூசி பதிவு",
    v_rec4_desc: "பார்மசி பிளஸ் • நோய்த்தடுப்பு",
    v_rec4_date: "செப் 01",
    p_title: "மெட்-வால்ட்",
    p_patient_id: "நோயாளி ஐடி: #29402",
    p_verified: "சரிபார்க்கப்பட்ட நோயாளி",
    p_grp_account: "கணக்கு",
    p_personal_info: "தனிப்பட்ட தகவல்",
    p_med_records: "மருத்துவ பதிவுகள்",
    p_insurance: "காப்பீடு",
    p_grp_pref: "விருப்பங்கள்",
    p_language: "மொழி",
    p_notifications: "அறிவிப்புகள்",
    p_security: "பாதுகாப்பு",
    p_grp_support: "ஆதரவு",
    p_help: "உதவி மையம்",
    p_contact: "தொடர்பு கொள்ள",
    p_signout: "வெளியேறு"
  },
  te: {
    nav_home: "హోమ్",
    nav_records: "రికార్డులు",
    nav_visits: "సందర్శనలు",
    nav_profile: "ప్రొఫైల్",
    nav_health: "ఆరోగ్యం",
    h_title: "మెడ్-వాల్ట్",
    h_greeting: "నమస్కారం",
    h_sub_greeting: "ఈ రోజు మీ శక్తి అద్భుతంగా ఉంది. ఇక్కడ మీ ఆరోగ్య స్థూలదృష్టి ఉంది.",
    h_upload_new: "కొత్తది అప్‌లోడ్ చేయండి",
    h_upload_desc: "వాల్ట్‌కి జోడించండి",
    h_view_vault: "వాల్ట్ చూడండి",
    h_view_desc: "రికార్డులను యాక్సెస్ చేయండి",
    h_med_tracker: "మెడిసిన్ ట్రాకర్",
    h_view_all: "అన్నీ చూడండి",
    h_med1_name: "లిసినோప్రిల్",
    h_med1_desc: "10mg • అల్పాహారం తర్వాత",
    h_med2_name: "విటమిన్ D3",
    h_med2_desc: "5000 IU • రాత్రి భోజనంతో",
    h_next_visit: "తదుపరి సందర్శన",
    h_visit1_tag: "రాబోయేది",
    h_visit1_title: "డాక్టర్ సారా జెంకిన్స్",
    h_visit1_desc: "సాధారణ తనిఖీ • ఉదయం 10:00",
    h_visit2_tag: "పెండింగ్‌లో ఉంది",
    h_visit2_title: "ల్యాబ్ ఫలితాలు",
    h_visit2_desc: "రక్త ప్యానెల్ • రేపు ఆశించబడుతోంది",
    v_title: "హెల్త్ వాల్ట్",
    v_header: "నా రికార్డులు",
    v_desc: "మీ పూర్తి వైద్య చరిత్రను ఒకే సురక్షిత ప్రదేశంలో నిర్వహించండి.",
    v_search: "రికార్డులు, తేదీలు లేదా డాక్టర్లను వెతకండి...",
    v_month1: "అక్టోబర్ 2023",
    v_rec1_title: "సమగ్ర రక్త ప్యానెల్",
    v_rec1_desc: "డాక్టర్ సారా జెంకిన్స్ • ల్యాబ్ నివేదిక",
    v_rec1_date: "అక్టో 24",
    v_rec2_title: "ఛాతీ ఎక్స్-రే స్కాన్లు",
    v_rec2_desc: "సిటీ జనరల్ హాస్పిటల్ • రేడియాలజీ",
    v_rec2_date: "అక్టో 12",
    v_month2: "సెప్టెంబర్ 2023",
    v_rec3_title: "వార్షిక శారీరక సారాంశం",
    v_rec3_desc: "డాక్టర్ రాబర్ట్ చెన్ • సాధారణ అభ్యాసం",
    v_rec3_date: "సెప్టెం 05",
    v_rec4_title: "టీకా రికార్డు",
    v_rec4_desc: "ఫార్మసీ ప్లస్ • రోగనిరోధకత",
    v_rec4_date: "సెప్టెం 01",
    p_title: "మెడ్-వాల్ట్",
    p_patient_id: "రోగి ID: #29402",
    p_verified: "ధృవీకరించబడిన రోగి",
    p_grp_account: "ఖాతా",
    p_personal_info: "వ్యక్తిగత సమాచారం",
    p_med_records: "వైద్య రికార్డులు",
    p_insurance: "భీమా",
    p_grp_pref: "ప్రాధాన్యతలు",
    p_language: "భాష",
    p_notifications: "నోటిఫికేషన్లు",
    p_security: "భద్రత",
    p_grp_support: "మద్దతు",
    p_help: "సహాయ కేంద్రం",
    p_contact: "మమ్మల్ని సంప్రదించండి",
    p_signout: "సైన్ అవుట్"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('en');

  const t = (key) => {
    return translations[language]?.[key] || translations['en'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
